### ISSUE TITLE
proguard rules for release build

### ISSUE THREAD

**Issue by orionlee** [retrostreams/android-retrofuture#1]
After replacing jdk8 `CompletableFuture with the version from `android8-retrofuture`, proguard stops during release build.

For now I can workaround it by suppressing all proguard warnings as follows.
> `-dontwarn java9.**`

It'd be great if there is some documentation on proper settings (or bundle proguard rules).

Environment: android gradle v3.1.2, minSDK 19, targetSDK 27

---
Excerpt of the warnings proguard gave:
```
Warning: java9.util.ArrayDequeSpliterator: can't find referenced class sun.misc.Unsafe
...
Warning: java9.util.concurrent.CompletableFuture: can't find referenced class sun.misc.Unsafe
...
Note: java9.util.ArraysArrayListSpliterator: can't find dynamically referenced class java.util.Arrays$ArrayList
Note: java9.util.HMSpliterators: can't find dynamically referenced class java.util.HashMap$Values
...

Note: java9.util.HMSpliterators$HashMapSpliterator accesses a declared field 'key' dynamically
      Maybe this is program field 'java9.util.KeyValueHolder { java.lang.Object key; }'
      Maybe this is library field 'android.R$attr { int key; }'
...

Note: java9.util.HMSpliterators$HashMapSpliterator accesses a declared field 'value' dynamically
      Maybe this is program field 'java9.util.KeyValueHolder { java.lang.Object value; }'
      Maybe this is program field 'java9.util.Optional { java.lang.Object value; }'
...

Note: java9.util.HMSpliterators accesses a declared field 'this$0' dynamically
      Maybe this is program field 'android.arch.core.internal.SafeIterableMap$IteratorWithAdditions { android.arch.core.internal.SafeIterableMap this$0; }'
...


```

**Comment by stefan-zobel** [comment]
Hi Sam Lee @orionlee

`-dontwarn java9.**
`

is correct. In general, you shouldn't try to obfuscate or shrink any of the android-retro... or streamsupport jars unless you know exactly what you are doing (and have tests that prove that everything still works at runtime) which, honestly, is quite unlikely.

Proguard with default settings doesn't have the slightest clue what it is (not) allowed to do or which classes are actually used at runtime and which are not.
So, please leave the jars untouched.

Off the top of my head something like the following should work

```
-keep class java9.** { *; }
-keep interface java9.** { *; }
-dontwarn java9.**
```


Maybe also throw in

```
-dontobfuscate  java9.**
-dontshrink  java9.**

-keepattributes Signature
-keepattributes *Annotation*
-keepattributes InnerClasses
-keepattributes SourceFile
-keepattributes LineNumberTable

```
(not sure if this is the correct syntax)

I'm running the test-suite with the debug builds, so I don't have to fiddle with the Proguard settings.
But you are right, I should document this somewhere. It may take some time but it's on my list now.

Please let me know if you experience any further problems.

Regards,
Stefan
